name: u16
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  age_calculator: ^1.0.0
  auto_route: ^6.0.0+1
  cached_network_image: ^3.2.3
  extended_image: ^7.0.2
  extended_nested_scroll_view: ^6.0.0
  flex_seed_scheme: ^1.2.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  flutter_riverpod: ^2.3.2
  flutter_svg: ^2.0.4
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  loading_overlay: ^0.3.0
  logger: ^1.3.0
  pull_to_refresh_notification: ^3.0.0
  riverpod_annotation: ^2.0.1
  sign_in_with_apple: ^4.3.0
  supabase_flutter: ^1.5.0
  validators: ^3.0.0

dev_dependencies:
  auto_route_generator: ^6.0.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.2
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5
  very_good_analysis: ^4.0.0+1

flutter_gen:
  output: lib/src/gen/

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env/
    - assets/images/
#    - assets/fonts/

